project:
  resources:
  - googleb8ffeae2840b0dfa.html
  type: website
  output-dir: output-web
  pre-render:
    - python scripts/build.py --generate-only
    - python scripts/generate_chapters.py
  render:
    - index.qmd
    - content/frontmatter/preface.qmd
    - content/frontmatter/methodology.qmd
    - content/frontmatter/contact.qmd
    - content/indexes/scripture-index.qmd

    # - content/books/*.qmd
    # - content/indexes/*.qmd
    - "*/index.qmd"
    - "*/*/index.qmd"

website:
  title: "The Key Verse of Every Chapter of the Bible"
  site-url: "https://gisjames.github.io/keyversebible/"
  description: "Discover a representative key verse from every chapter of the Bible, with chapter insights, explanations, and book summaries."


  search: true
  open-graph: true
  twitter-card: true

  navbar:
    title: "Key Verse Bible"
    left:
      - href: index.qmd
        text: Home
      - href: content/frontmatter/methodology.qmd
        text: Methodology
      - href: content/indexes/scripture-index.qmd
        text: Scripture Index
      - href: content/frontmatter/contact.qmd
        text: Contact

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles/bible.css
    toc: true
    toc-depth: 3
    canonical-url: true
